### ISSUE TITLE
[建议]使用 dart-sass 替代 node-sass

### ISSUE THREAD

**Issue by ModyQyW** [hug-sun/element3#251]
基于 libsass 的 node-sass 将被弃用，官方建议改用 [dart-sass](https://github.com/sass/dart-sass)。见 [LibSass is Deprecated](https://sass-lang.com/blog/libsass-is-deprecated)。

**Comment by GCGligoudan** [comment]
node-sass下载编译经常出错

**Comment by ModyQyW** [comment]
> node-sass下载编译经常出错

这个只是网络问题，使用[mirror-config-china](https://www.npmjs.com/package/mirror-config-china)即可。

**Comment by GCGligoudan** [comment]
这个跟cnpm有什么区别

**Comment by GCGligoudan** [comment]
> > node-sass下载编译经常出错
> 
> @GCGligoudan 这个只是网络问题，使用[mirror-config-china](https://www.npmjs.com/package/mirror-config-china)即可。

这个跟cnpm有什么区别？

**Comment by ModyQyW** [comment]
> > > node-sass下载编译经常出错
> > 
> > 
> > @GCGligoudan 这个只是网络问题，使用[mirror-config-china](https://www.npmjs.com/package/mirror-config-china)即可。
> 
> 这个跟cnpm有什么区别？

cnpm 可能会有奇怪的bug。mirror-config-china 只是把特定依赖的源指定为淘宝源。一般建议用npm/yarn + mirror-config-china。

**Comment by xxyuk** [comment]
不是依赖的锅，安装失败 使用 cnpm 或者换淘宝源就行了 或者穿墙 一劳永逸

**Comment by GCGligoudan** [comment]
> > node-sass下载编译经常出错
> 
> @GCGligoudan 这个只是网络问题，使用[mirror-config-china](https://www.npmjs.com/package/mirror-config-china)即可。

其实是node-sass不同的版本对环境node版本有要求。所以最好的办法就是不用sass

**Comment by chang-ke** [comment]
> > > node-sass下载编译经常出错
> > 
> > 
> > @GCGligoudan 这个只是网络问题，使用[mirror-config-china](https://www.npmjs.com/package/mirror-config-china)即可。
> 
> 其实是node-sass不同的版本对环境node版本有要求。所以最好的办法就是不用sass

同意不用sass哈哈哈哈，less也不错啊

**Comment by ShoneSingLone** [comment]
建议使用less，添加在线编译

**Comment by LuoRiWuSheng** [comment]
node-sass 经常编译不过，有一个重要的原因就是 node 版本问题 不能太高， 14以上我的 node-sass 就编译不过

**Comment by Happylife56** [comment]
> node-sass下载编译经常出错

可以在项目中改变下你的镜像，在项目中添加文件   .npmrc或者 .yarnrc 

```
# .npmrc  .yarnrc  
registry "https://registry.npm.taobao.org"
sass_binary_site "https://npm.taobao.org/mirrors/node-sass/"

```

**Comment by ModyQyW** [comment]
这个 issue 的本意是建议用 dart-sass 替代node-sass，而不是建议用 less 替代 sass 或者指导用户如何安装 node-sass。最近的回复已经偏离了我开这个 issue 的本意，所以我决定关闭这个issue。
