### ISSUE TITLE
这块useButtonSize不是在调用之后定义吗  我这里报错

### ISSUE THREAD

**Issue by HomyeeKing** [hug-sun/element3#254]
https://github.com/kkbjs/element3/blob/2276e55e7273fe4afa794501f7ce32361bde304a/packages/button/Button.vue#L76

![image](https://user-images.githubusercontent.com/49113249/97857017-15707e00-1d38-11eb-82dc-0e4a142cbbd2.png)

**Comment by cuixiaorui** [comment]
如果可以的话，请提供一个线上可复现 bug 的 demo 地址

这样可以方便我们尽快的解决问题

tips:
- 暂时还没有做对 ts 的支持
