### ISSUE TITLE
组件check流程

### ISSUE THREAD

**Issue by ImJustAMan** [hug-sun/element3#323]
### 大体流程

这块我说一下我认为比较好的check流程，如果你有更好更快捷的流程欢迎来回复，只要效果好，没有不可以。

首先在这里再次说明一下check所要做的两件最重要的事情

1. 确保文档中的demo均书写无误并修改为vue3版本代码
2. 确保文档中api与组件对外暴露api一致

这两点就是咱们check组件的核心任务。

这两点有一个交集，其实就是文档demo，由于demo就是用来演示api使用的，所以按照demo一个一个往下捋是我认为最简单也是最快捷的方式。

- 从第一个demo开始往下梳理，将每个demo改为vue3版本并保证最终渲染效果无报错无bug同时实现对应效果
- 确认其中所使用该组件api与文档最下方文档所写内容一致，同时保证组件对外暴露api相同
- `emit`事件最佳使用是烤肉串命名例如`emit('item-change')`，遂组件内部若出现驼峰命名`emit('itemChange')`请记得将其改为烤肉串命名方式
- 最后提示几点比较容易忽略的点，这两个点很有可能会导致你组件无报错但无效果
  - 第一个是当使用了`v-model`时，vue3版本的双向绑定已经使用的是`modelValue`变量(具名`v-model`除外：`v-model:visible`)
  - 第二个是`slot`使用的变化，vue3版本对于插槽的使用改动了，原本`<template slot="{}">`现在优化为了`<template v-slot="{}">`，对于具名插槽`<template slot="error">`改为`<template v-slot:error>`或`<template #error>`。

### 举个例子

之前`Avatar`组件有一个问题：

```vue
<!-- 文档中demo -->
<template>
  <div class="demo-type">
    <el-avatar :size="60" src="https://empty" @error="errorHandler">
      <img src="https://cube.elemecdn.com/e/fd/0fc7d20532fdaf769a25683617711png.png"/>
    </el-avatar>
  </div>
</template>
<script>
  export default {
    setup(){
      const errorHandler=()=>{
        return true
      }
      return {
        errorHandler
      }
    }
 
  }
</script>
```

### Events

| 事件名 | 说明                                                         | 回调参数   |
| :----- | :----------------------------------------------------------- | :--------- |
| error  | 图片类头像加载失败的回调， 返回 false 会关闭组件默认的 fallback 行为 | (e: Event) |

在文档中`error`作为事件，并将`Event`事件对象作为参数传递，但在组件中实际写法为：

```js
// props
props: {
  error: Function
}
// error处理函数
const handleError = () => {
  const errorFlag = error?.value()
  if (!!errorFlag !== false) {
    isImageExist.value = false
  }
}
```

其中`error`作为父组件传递的属性来使用，并未用到`emit`等触发父组件的事件，所以在文档中`error`就应改为`:error`进行传递或修改组件内部逻辑，但此处逻辑修改可能会比较复杂，所以我们修改文档即可，并且原本的处理函数并未传递事件对象给外层，所以此处在组件中我们也需要将事件对象传递。所以修改完成就是这样：

```vue
<!-- 文档中demo -->
<template>
  <div class="demo-type">
    <el-avatar :size="60" src="https://empty" :error="errorHandler">
      <img src="https://cube.elemecdn.com/e/fd/0fc7d20532fdaf769a25683617711png.png"/>
    </el-avatar>
  </div>
</template>
<script>
  export default {
    setup(){
      const errorHandler=()=>{
        return true
      }
      return {
        errorHandler
      }
    }
 
  }
</script>

<!-- 组件error处理函数 -->
const handleError = (e) => {
  const errorFlag = error?.value(e)
  if (!!errorFlag !== false) {
    isImageExist.value = false
  }
}
```

**Comment by cuixiaorui** [comment]
对应的视频教程链接[传送门](https://www.bilibili.com/video/BV1Gf4y1q7xv)

**Comment by amadeus711** [comment]
**github pr 关联 issues**

将pr的URL评论在对应的issues下即可

**Comment by cuixiaorui** [comment]
已经完美完成任务
