### ISSUE TITLE
NavMenu组件中开启router点击报错

### ISSUE THREAD

**Issue by CN-GGEZ** [hug-sun/element3#352]
- 开启router跳转后点击并未实现路由跳转

![image](https://user-images.githubusercontent.com/58074247/99058244-e5e33080-25d7-11eb-9778-b2f3bbf8c173.png)

- 报错如下

![image](https://user-images.githubusercontent.com/58074247/99057813-3f972b00-25d7-11eb-88ca-b0cf3c84e5ff.png)

- 查看源码后发下组件在对route进行取值时有误

![image](https://user-images.githubusercontent.com/58074247/99057591-f8a93580-25d6-11eb-9ac7-d6a82dbd888a.png)

- 建议新增一下item.props.index

![image](https://user-images.githubusercontent.com/58074247/99058004-87b64d80-25d7-11eb-8ebf-225518b12f28.png)

**Comment by cuixiaorui** [comment]
感谢

在处理
