### ISSUE TITLE
input设置style

### ISSUE THREAD

**Issue by yss670660798** [hug-sun/element3#390]
input设置样式没有在外层div上，在input上，外层没有容器宽度还是100%
![微信截图_20201121000240](https://user-images.githubusercontent.com/19487308/99821523-210fd180-2b8d-11eb-8364-14d367f196f1.png)
![微信截图_20201121000309](https://user-images.githubusercontent.com/19487308/99821541-2705b280-2b8d-11eb-9091-724e7ea8188c.png)

**Comment by ocean-liang** [comment]
https://github.com/hug-sun/element3/pull/395

**Comment by cuixiaorui** [comment]
已经修复
