### ISSUE TITLE
疑似完整抄袭 Element Plus 的代码

### ISSUE THREAD

**Issue by xxyuk** [hug-sun/element3#396]
最近做公司项目在调研支持 Vue3 的 UI 库，发现除了 Element UI 的官方升级版 Element Plus 之外还有这个库，对比了一下代码发现，你们虽然标榜自己是独立维护的项目，为什么UI库里最核心的 table 组件，完完全全照抄了官方版本的代码呢

这是 ele3 的 tabele 代码 https://github.com/hug-sun/element3/tree/master/packages/table/src

这是 element plus 的 代码 https://github.com/element-plus/element-plus/tree/dev/packages/table/src 这里提交时间明显早了许多
可以看到不管是目录结构 还是代码命名 逻辑 格式 缩进，基本就是复制粘贴，

我并不觉得这是一个开源项目应该有的态度，能请维护者说明解答一下我的疑惑吗。

多谢

**Comment by shengxinjing** [comment]
@xxyuk 我去确认一下给你答复

**Comment by shengxinjing** [comment]
从格式看到我们的开发者提PR借鉴了element-plus的代码 但是没有声明，我会马上加上声明，并且会尽快考虑重写
感谢提出， 我明天会核查一下其他组件
element3是一个教育驱动的UI框架， 最初我把工程化更新到vue3 主要工作就是merge众多想学习vue3组件化开发者的pr ，有任何借鉴别人代码的 发现后我都会主动声明

**Comment by shengxinjing** [comment]
![image](https://user-images.githubusercontent.com/1905176/99905352-432f5e00-2d0b-11eb-9dde-61770530f026.png)
已加声明，感谢提出

**Comment by xxyuk** [comment]
感谢维护者回复。

还有另一个疑问，能看出来本项目是 fork element-ui 而来，为何不按照开源生态的游戏规则 fork 一份代码，而是直接在别人的代码库上修改呢。

比如 element 项目的 5000 多条迭代的 commits 以及 500 多名贡献者 
<img width="136" alt="image" src="https://user-images.githubusercontent.com/42378428/99905522-39f2c100-2d0c-11eb-9e4f-4bd50f699233.png">

<img width="316" alt="image" src="https://user-images.githubusercontent.com/42378428/99905534-5262db80-2d0c-11eb-846f-bfdc3a362263.png">

这样不仅会给像我这样的初次访问者一个误导，以为 ele3 已经有如此多的贡献者和迭代次数，以及能看到 element 官方人员的头像，错误理解项目的归属和维护人员。

同时，这也是 Github 官方非常不建议的行为，因为这会误导官方的排名系统（主要依据 star commits contributors 的综合分数），如果发现可能会受到惩罚，相信也不是这个项目期待的。

**Comment by cuixiaorui** [comment]
十分感谢帮助我们指出问题

我刚看了一下 table 的实现，确实是参考了大量的 plus 的代码

组件重构计划我们是在排期中的

后面我们会一个一个组件的进行重构

**Comment by shengxinjing** [comment]
@xxyuk 
你说的这个模式，最早是这么想的，地址在这里 https://github.com/hug-sun/element， 后来我们觉得 用了element-ui的代码，保存fork和记录是一个比较尊重别人贡献的决定， 比如https://github.com/Meituan-Dianping/mpvue是改造vue的runtime去适配小程序，就保留了尤大所有的记录，我们就重新fork了一份，保留了所有contributor
毕竟我们这个项目就是在element-ui的基础之上改造，并不是从0写的

**Comment by xxyuk** [comment]
感谢回复，

但二者其实略有不同， mpvue  是拓展了 vue 的生态，而本项目更多是在和 element 官方竞争市场，那么用别人已经取得的成绩和原团队竞争，是不是有些不太好。

真说尊重别人贡献的话，不是反而应该使用 github 的 fork 功能来标记仓库关系吗

**Comment by shengxinjing** [comment]
额，我们其实最早也是要扩展这个生态， 创建element3的时候，还不知道plus的存在，element2已经半年没有更新了，最初就是扩展element的生态， element官方放了element-plus的链接，大概是最近一个月的事情吧，  我们并不是竞争，我们的目的是帮助开发者pr的方式，学习组件化这件事情  
最初的想法可以看这个知乎回答   https://www.zhihu.com/question/366200594/answer/1384351977   

而且我刚看了一下，plus的contributor里，也没有看到element-ui官方团队的成员，可以理解为是官方认可的社区版
readme里加plus的commit在这里， 一个月前刚加的 
https://github.com/ElemeFE/element/commit/eb1c2c57704a726f93ef2943d6a31d8e3aa9006a

我们本身也无意竞争， 最早我们是叫giao-ui， 单纯了为了帮助大家学习vue3的组件化 ，到现在也是一个为了学习的UI框架

**Comment by xxyuk** [comment]
多谢回复，但据我所知，之所以“看起来没有官方成员”只是因为 element 最初几位大佬已经离职了，element plus 的几个维护者仍然还是现饿了么大前端团队的在职人员，只是可能没那么面熟而已。

**Comment by shengxinjing** [comment]
那只能归结为小号了。。element官方团队还在职的只有iamkun昆哥一个人在了，早起team的人我都知道，但是现在plus里没看到，关于element3我还和昆哥通过电话，对方也表示我们为了教育的组件库路线表示认可， 现在plus没有对外公开的member，我也不太清楚为啥
![image](https://user-images.githubusercontent.com/1905176/99906641-3151b900-2d13-11eb-8d2b-2ae25151b1b9.png)

**Comment by xxyuk** [comment]
成员问题我们就不扩展了，毕竟不是公开信息 总之还是期待开源市场可以理性竞争 共同繁荣

**Comment by shengxinjing** [comment]
感谢感谢， 我们也会争取及时和官方同步信息，做好这个for learn的组件库

**Comment by cuixiaorui** [comment]
其实我们团队做这个库的点很明确

就是开开心心写代码 好好学习 天天向上

没想着和谁竞争 

table 组件近期我会重新实现

如果还有别的代码和 plus 一致的话，欢迎继续指出
