### ISSUE TITLE
Container 布局容器样式失效

### ISSUE THREAD

**Issue by cuixiaorui** [hug-sun/element3#397]
Container 布局容器样式失效问题：

现在：
![image](https://user-images.githubusercontent.com/12064746/99933860-30fb0180-2d97-11eb-9021-d0b20120b3b0.png)

期望：
![image](https://user-images.githubusercontent.com/12064746/99933899-4ff99380-2d97-11eb-90fd-fc6366023b6b.png)

**Comment by ocean-liang** [comment]
可以贴下代码?
