### ISSUE TITLE
progress 组件 自定义颜色方法中  getCurrentInstance().ctx 这个

### ISSUE THREAD

**Issue by vitekarson** [hug-sun/element3#400]
![image](https://user-images.githubusercontent.com/73568290/100062615-d7fc9d80-2e6a-11eb-999a-cbc2f375722b.png)

IMPORTANT: Please use the following link to create a new issue:

  https://elementui.github.io/issue-generator

If your issue was not created using the app above, it will be closed immediately.
-->

**Comment by cuixiaorui** [comment]
没看懂什么问题

请描述清楚哈

你期望的是什么

**Comment by vitekarson** [comment]
这个没有看到在哪里引用

**Comment by cuixiaorui** [comment]
这是 vue3 获取当前组件实例的方法

具体可以查看 vue3 官方文档来进行学习
