### ISSUE TITLE
官方文档移除其他语言 md 文档，仅保留中文文档

### ISSUE THREAD

**Issue by qiqingfu** [hug-sun/element3#408]
**需求目标：** 
给文档官网作减法，保留其最核心的功能，在构建过程中减少打包资源的体积，加快编译速度。

**当前项目：** 
1. 打包时会在 `examples/pages/` 目录下生成多语言的 Element3 官网文件
2. `examples/docs` 目录下存在多语言组件 *.md 文档
3. 多语言路由 routes
4. 多语言切换

**期望项目：** 
1. 打包时在 `examples/pages/` 目录下仅生成 `zh-CN` 官网文件
2. 移除 `examples/docs` 下非 `zh-CN` 的 *.md 文档
3. 只生成 `zh-CN` routes
4. 移除多语言切换

**项目体积及构建速度：** 
- 包体积：
before：47.6 MB，300+ 文件
after：24.6MB，90+ 文件

- 速度：
before：大概为 30384ms
after：大概为 16010ms

**Comment by qiqingfu** [comment]
**项目体积：** 
移除其他语言文档之前打包的项目体积为：47.6 MB，300+ 文件

移除之后打包的项目体积为：24.6MB，90+ 文件

**Comment by cuixiaorui** [comment]
good job
