### ISSUE TITLE
文档卡片错误

### ISSUE THREAD

**Issue by GuCangRan** [hug-sun/element3#418]
https://element3-ui.com/#/zh-CN/component/card
文档中关于 卡片基础用法 插槽错误,显示不正确

**Comment by cuixiaorui** [comment]
可否提供一个可复现问题的 demo？

**Comment by GuCangRan** [comment]
我本来想截图,但是无法发送,&nbsp;我说文档中卡片这个插槽部分应该书写不对,显示错位了&nbsp;是文档这的问题







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "春去春又来"<notifications@github.com&gt;; 
发送时间: 2020年11月27日(星期五) 下午4:03
收件人: "hug-sun/element3"<element3@noreply.github.com&gt;; 
抄送: "张彦瑞"<1067454662@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [hug-sun/element3] 文档卡片错误 (#418)





 
可否提供一个可复现问题的 demo？

**Comment by GuCangRan** [comment]
我是在说您这边提供的手册, 那个显示卡片不对, 是插槽用法不对导致您这边文档上的错误

**Comment by wulinsheng123** [comment]
> 我是在说您这边提供的手册, 那个显示卡片不对, 是插槽用法不对导致您这边文档上的错误

可以提供下你错误的内容吗我本地没有看到

**Comment by GuCangRan** [comment]
您这边官网地址：&nbsp;https://element3-ui.com/#/zh-CN/component/card
官方错误截图：


正确的卡片应该：

**Comment by GuCangRan** [comment]
> > 我是在说您这边提供的手册, 那个显示卡片不对, 是插槽用法不对导致您这边文档上的错误
> 
> 可以提供下你错误的内容吗我本地没有看到

我已经回复给您这边邮箱中了，有截图对比，如果收不到可以留下邮箱地址我再次发送

**Comment by GuCangRan** [comment]
> > 我是在说您这边提供的手册, 那个显示卡片不对, 是插槽用法不对导致您这边文档上的错误
> 
> 可以提供下你错误的内容吗我本地没有看到
错误展示：
![d5ccd5fe16c8e3370589619ba41fce11](https://user-images.githubusercontent.com/68489862/100538027-34dfc580-3268-11eb-9f58-f4af5f834ce3.png)
正确展示
![96323c0033d4d58b9e708562fdff74f4](https://user-images.githubusercontent.com/68489862/100538030-3dd09700-3268-11eb-8e36-bb7ffa22f15a.png)

**Comment by wulinsheng123** [comment]
> > > 我是在说您这边提供的手册, 那个显示卡片不对, 是插槽用法不对导致您这边文档上的错误
> > 
> > 
> > 可以提供下你错误的内容吗我本地没有看到
> > 错误展示：
> > ![d5ccd5fe16c8e3370589619ba41fce11](https://user-images.githubusercontent.com/68489862/100538027-34dfc580-3268-11eb-9f58-f4af5f834ce3.png)
> > 正确展示
> > ![96323c0033d4d58b9e708562fdff74f4](https://user-images.githubusercontent.com/68489862/100538030-3dd09700-3268-11eb-8e36-bb7ffa22f15a.png)

收到

**Comment by wulinsheng123** [comment]
![image](https://user-images.githubusercontent.com/27261522/100809731-c706ea00-3471-11eb-88a6-34a1449a4246.png)
这样写就可以了我试过了，已经推上去过了

**Comment by cuixiaorui** [comment]
done
