### ISSUE TITLE
element 原人员已开始其vue3升级😆

### ISSUE THREAD

**Issue by goYou** [hug-sun/element3#433]
Existing Component
否

Component Name
ele3

Description
element已经开始vue3升级了 https://github.com/element-plus/element-plus 
期待你们双方的完善

**Comment by cuixiaorui** [comment]
我们库是教学和研发一体的

组件库会按照工业级别来写

同时会产出大量的文章和视频教程

为前端社区做出贡献

可以理解我们和 plus 没有什么冲突

他们做他们的，我们做我们的

欢迎使用哈，有任何问题和需求我们都会及时跟进
