### ISSUE TITLE
[bug] el-input组件bug

### ISSUE THREAD

**Issue by woshidamimi** [hug-sun/element3#434]
当一个页面有两个el-input，一个是隐藏状态，一个是显示状态，当在显示的el-input输入文字时，隐藏的那个el-input会显示出来，如果给el-input添加style属性则不会出现这个bug

**Comment by cuixiaorui** [comment]
可否提供一个可复现问题的 demo？

**Comment by woshidamimi** [comment]
> 可否提供一个可复现问题的 demo？


之前的bug现在没法重现了，现在的input组件如果在第一个输入框里面输入文字，其他的v-show=false的输入框样式会一直被更新

代码如下
```
<template>
  <div class="box">
    <el-input v-model="inputValue"></el-input>
    <el-input v-show="false" v-model="inputValue1"></el-input>
    <el-input v-show="false" v-model="inputValue2"></el-input>
  </div>
</template>
<script>
import { ref } from "vue";
export default {
  name: "Login",
  setup() {
    let inputValue = ref("");
    let inputValue1 = ref("");
    let inputValue2 = ref("");
    return {
      inputValue2,
      inputValue1,
      inputValue
    };
  }
};
</script>
<style lang="css">
.box{
    width: 300px;
    margin: 20px auto;
}
</style>

```

**Comment by woshidamimi** [comment]
多次测试我发现只要是显示中的input（原生或者el-input）输入文字都会触发v-show=false的el-input的style更新

**Comment by WumaCoder** [comment]
BUG原因：

**Comment by WumaCoder** [comment]
BUG原因：
![image](https://user-images.githubusercontent.com/39021696/101246599-56045280-374f-11eb-98e0-70f5770e2a37.png)

**Comment by WumaCoder** [comment]
原因正在找

**Comment by WumaCoder** [comment]
如果你给el-input设置一个style这个bug就没有了

**Comment by WumaCoder** [comment]
如果你给el-input设置一个style这个bug就没有了

**Comment by woshidamimi** [comment]
> 如果你给el-input设置一个style这个bug就没有了

之前我也是这样加的，但是后来又无法重现了，也许是版本原因。现在出现了新的bug，我已经在评论里面说了一下。源码看起来好复杂，只能等待各位大佬修复了。

**Comment by cuixiaorui** [comment]
这个问题将会在 0.0.29 版本修复

**Comment by WumaCoder** [comment]
https://juejin.cn/post/6903797122647195655
