### ISSUE TITLE
refactor input tasking

### ISSUE THREAD

**Issue by ocean95966** [hug-sun/element3#467]
### tasking
- [x] 可以设置input框类型 支持input原生的类型,默认是text
- [x] 可以绑定值
  * 类型是string / number,双向绑定
- [x] 可以设置最大值, 超过最大值后无法输入
- [x] 可以设置最小值, 不满足条件显示错误不给提交
- [x] 可以显示输入字数统计
  * 显示当输入的字数和最大可以输入字数, 超过不给输入
  * 只对text/textarea类型有效
- [x] 可以设置输入框占位文本, 不输入内容时显示这个值
- [x] 可以设置是否禁用输入框,禁用后不可输入只能显示.默认不禁用
- [x] 可以设置输入框尺寸，只在 `type!="textarea"` 时有效,可以取值(medium / small / mini)
- [x] 可以显示输入框头部图标,输入图标类型,则在输入框前面显示图标
- [x] 可以显示输入框尾部图标,输入图标类型,则在输入框后面显示图标
- [x] 可以控制输入框行数，只对 `type="textarea"` 有效
- [x] 可以设置自适应内容高度(`type="textarea"` 有效)
  * 输入对象的时候{ minRows: 2, maxRows: 6 },对应的是textarea clo row属性
  * 输入布尔值true的时候可以自由改变大小
- [x] 可以设置自动补齐
- [x] 可以设置原生属性 (name	readonly	max	min	step	resize	autofocus	form	原生属性	label	tabindex)
- [x] 可以控制输入时是否触发表单的校验, 当值为true的时候会触发form的validate
- [x] 可以控制输入框的显示内容(只对 `type="text"` 有效)
  * 输入框头部内容
  * 输入框尾部内容
  * 输入框前置内容
  * 输入框后置内容
- [x] 可以设置在 Input 失去焦点时触发的回调函数,该函数的参数包含输入框event事件
- [x] 可以设置在 Input 获取焦点时触发的回调函数,该函数的参数包含输入框event事件
- [x] 可以设置在 Input 失去焦点或用户按下回车时的回调函数,该函数的参数包含输入框event事件
- [x] 可以设置在 Input 值改变时的回调函数,该函数的参数包含输入框的值
- [x] 可以设置input 清空输入值的回调函数
- [x] 可以触发input的focus函数使input 获取焦点
- [x] 可以触发input的blur函数使 input 失去焦点
- [x] 可以触发input的select函数使 input select 文字

### Problems
*  单元测试覆盖率问题(已经手工确认已经执行过, 但是测试报告显示没有覆盖到  packages/input/ use.js     |    87.8 |    75.76 |   83.87 |   88.61 | 28,50,63,140,144,148,185-187)

**Comment by cuixiaorui** [comment]
```
在模板里面使用bind预设参数会失效
<input @blur="onBlur.bind(null, 'blur')" /> // 无效
```
为什么要用 bind 呢？

你想要做什么？

**Comment by ocean95966** [comment]
> ```
> 在模板里面使用bind预设参数会失效
> <input @blur="onBlur.bind(null, 'blur')" /> // 无效
> ```
> 
> 为什么要用 bind 呢？
> 
> 你想要做什么？

我有两个子组件都有同样的行为 onBlur onChange onInput onFous 其实他们都是做了同样的事情 所以想父组件抽出了一个函数 onEventHandle(type, event) 子组件只管传递type和event就行了, 但是在模板的用法用@语法第一个参数就是event, 所以想给onEventHandle预设一个参数 type
```html
<input @blur="onEventHandle" />   
```
在模板里面
```html
// chilrden.vue
<input @blur="onEventHandle.bind(null, 'blur')" />   // 无效
```
```javascript
// chilrden.vue
   setup() {
       const onblur = onEventHandle.bind(null, 'blur')  // 能够正常使用
       return { 
           onblur
       }
  }
```
@cuixiaorui

**Comment by cuixiaorui** [comment]
看看文档 [v-on](https://cn.vuejs.org/v2/api/#v-on)


在监听原生 DOM 事件时，方法以事件为唯一的参数。如果使用内联语句，语句可以访问一个 
```js
$event property：v-on:click="handle('ok', $event)"。
```

$event
