### ISSUE TITLE
refactor Tag component

### ISSUE THREAD

**Issue by wulinsheng123** [hug-sun/element3#468]
###Target
完全兼容旧的属性、事件、方法

### Tasking

- [x] 通过`slot`的方式，定义Tag组件内容
- [x] 通过`props.type`控制Tag组件的主题样式，可选值[success/info/warning/danger/info]
- [x] 通过`props.size`控制Tag组件的尺寸，可选值[medium/small/mini/large]
- [x] 通过`props.effect`控制Tag组件的尺寸，可选值[dark/light/plain]
- [x] 通过`props.color`控制Tag组件的背景色
- [x] 通过`props.hit` 控制Tag组件边框描边
- [x] 通过`props.disableTransitions` 控制Tag禁用渐变动画
- [x] 通过`props.closable` 控制Tag组件可否关闭,关闭时有动画
- [x] 通过`click` 点击时触发的click事件
- [x] 通过`close` 点击时触发的close事件,关闭时通过内部状态,为false时隐藏

**Comment by cuixiaorui** [comment]
Tag 已经完成
