### ISSUE TITLE
打包后ctx指向不同导致组件报错（el-menu）

### ISSUE THREAD

**Issue by allan303** [hug-sun/element3#477]
环境:
"element3": "0.0.22",
"vue": "^3.0.4"
开发环境没问题(npm run serve)
打包之后出现（这里只选一部分）:
2runtime-core.esm-bundler.js:225 TypeError: Cannot read property 'dispatchEvent' of undefined
    at P (element3-ui.esm-bundler.js:25521)
    at Ae (runtime-core.esm-bundler.js:154)
    at Pe (runtime-core.esm-bundler.js:163)
    at HTMLLIElement.n (runtime-dom.esm-bundler.js:301)
Fe @ runtime-core.esm-bundler.js:225
He @ runtime-core.esm-bundler.js:203
Ae @ runtime-core.esm-bundler.js:157
Pe @ runtime-core.esm-bundler.js:163
n @ runtime-dom.esm-bundler.js:301
2element3-ui.esm-bundler.js:25533 Uncaught TypeError: v.ctx.closeMenu is not a function
    at element3-ui.esm-bundler.js:25533
(anonymous) @ element3-ui.esm-bundler.js:25533
2runtime-core.esm-bundler.js:225 TypeError: Cannot read property 'dispatchEvent' of undefined
    at P (element3-ui.esm-bundler.js:25521)
    at Ae (runtime-core.esm-bundler.js:154)
    at Pe (runtime-core.esm-bundler.js:163)
    at HTMLLIElement.n (runtime-dom.esm-bundler.js:301)
Fe @ runtime-core.esm-bundler.js:225
He @ runtime-core.esm-bundler.js:203
Ae @ runtime-core.esm-bundler.js:157
Pe @ runtime-core.esm-bundler.js:163
n @ runtime-dom.esm-bundler.js:301
element3-ui.esm-bundler.js:25533 Uncaught TypeError: v.ctx.closeMenu is not a function
    at element3-ui.esm-bundler.js:25533
(anonymous) @ element3-ui.esm-bundler.js:25533
element3-ui.esm-bundler.js:25517 Uncaught TypeError: v.ctx.openMenu is not a function
    at element3-ui.esm-bundler.js:25517
(anonymous) @ element3-ui.esm-bundler.js:25517
element3-ui.esm-bundler.js:25533 Uncaught TypeError: v.ctx.closeMenu is not a function
    at element3-ui.esm-bundler.js:25533
(anonymous) @ element3-ui.esm-bundler.js:25533
runtime-core.esm-bundler.js:225 TypeError: Cannot read property 'dispatchEvent' of undefined
    at P (element3-ui.esm-bundler.js:25521)
    at Ae (runtime-core.esm-bundler.js:154)
    at Pe (runtime-core.esm-bundler.js:163)
    at HTMLLIElement.n (runtime-dom.esm-bundler.js:301)
Fe @ runtime-core.esm-bundler.js:225
element3-ui.esm-bundler.js:25533 Uncaught TypeError: v.ctx.closeMenu is not a function
    at element3-ui.esm-bundler.js:25533

查看element3的源代码 （这里只选了一个）：
```
      dispatch('mouse-leave-child');
      clearTimeout(timeout.value);
      timeout.value = setTimeout(() => {
        !mouseInChild.value && rootMenu.ctx.closeMenu(index.value);
      }, hideTimeout.value);
```
这里代码里面的ctx应该和开发环境的ctx不一致了，导致出错。

参考Vue3的源代码：
`
  if (__DEV__) {
    instance.ctx = createRenderContext(instance)
  } else {
    instance.ctx = { _: instance }
  }
`

**Comment by allan303** [comment]
抱歉，发现这个bug已经修复了。
但是有个新的bug， build之后el-menu无法开关el-submenu(点击无反应)，dev环境一切正常。

**Comment by allan303** [comment]
感谢修复bug！  不过现在npm上面的0.0.30还是老的代码，有点郁闷。麻烦有时间时候更新一下，谢谢！

**Comment by cuixiaorui** [comment]
客气啦~~

明天早上会发版修复
