### ISSUE TITLE
version 0.0.29 can not get

### ISSUE THREAD

**Issue by guodonglw** [hug-sun/element3#480]

**Comment by guodonglw** [comment]
$ npm install element3@0.0.29
npm ERR! code ETARGET
npm ERR! notarget No matching version found for element3@0.0.29.

**Comment by cuixiaorui** [comment]
有点意思，0.0.29 是确实发布的

但是并没有找到

我会重新发布一版

**Comment by guodonglw** [comment]
> 有点意思，0.0.29 是确实发布的
> 
> 但是并没有找到
> 
> 我会重新发布一版

哈哈，好的，感谢，非常期待element3的最终稳定版本

**Comment by cuixiaorui** [comment]
问题找到了

是 npm registry 的问题

你先切换到官方源 在安装
```js
npm config set registry https://registry.npmjs.org 

npm i element3
```
这时候就 ok 了。

如果用淘宝源的话，确实是没有 0.0.29 版本
