### ISSUE TITLE
el-menu @select show different between development and production env

### ISSUE THREAD

**Issue by guodonglw** [hug-sun/element3#481]

**Comment by guodonglw** [comment]
<el-menu
      class="el-menu-vertical-demo"
      @select="handleSelect"
      :collapse="fold"
      router>


const handleSelect = (id) => {
      console.log('id:', id)
 }

in dev env
id: /homepage

in prod env
id: undefined

**Comment by zqy1151215064** [comment]
> <el-menu
> class =“ el-menu-vertical-demo”
> @select =“ handleSelect”
> ：collapse =“ fold”
> 路由器>
> 
> const handleSelect =（id）=> {
> console.log（'id：'，id）
> }
> 
> 在开发环境
> ID中：/ homepage
> 
> 在产品环境
> ID中：未定义

this issue will be fixed in version 0.0.31
