### ISSUE TITLE
table组件大约什么时候能符合vue3的调用方式呢？

### ISSUE THREAD

**Issue by guodonglw** [hug-sun/element3#494]

**Comment by cuixiaorui** [comment]
你是指的文档里面的使用 demo 吗？

自己改成 composition api 的写法也是 ok 的

**Comment by guodonglw** [comment]
> 你是指的文档里面的使用 demo 吗？
> 
> 自己改成 composition api 的写法也是 ok 的

我看到你们的demo演示里边用的还是老的写法，是代码版本已经支持vue3的方式了吗？

**Comment by cuixiaorui** [comment]
是支持的，你直接用 composition api 的写法就行

文档后面会更新成 composition api 的形式

也欢迎给我们 pr
