### ISSUE TITLE
website migrate

### ISSUE THREAD

**Issue by ocean95966** [hug-sun/element3#507]
## 目的
让 website 的技术栈升级到最新，删除废弃代码，精简代码逻辑，

## Tasking
- [x] 使用 vue-cli 创建最新的 vue3 项目
   - [x] vue-router
   - [x] e2e 选择 cypress
   - [x] unit test 选择 jest 
- [x] 移植代码到新的项目内
- [x] 保留play入口,用于调试
- [x] 目录结构要重新规划
- [x] 重新整理代码，删除废弃代码，只保留当前官网功能即可
- [x] 需要删除多语言的支持
   - [x] 目前我们只支持中文，之前的语言处理逻辑都可以干掉
- [x] 支持typescript

**Comment by cuixiaorui** [comment]
需要在 vue.config.js 里面增加几个配置

可参考一下配置
```js
const path = require('path')

module.exports = {
  chainWebpack: config => {
    config
      // 修改 entry 配置
      .entry('app')
      .clear()
      .add(path.resolve(__dirname, './entry.js'))
      .end()

// 添加解析 md 的 loader
    config.module
      .rule('md2vue')
      .test(/\.md$/)
      .use('vue-loader')
      .loader('vue-loader')
      .end()
      .use('md-loader')
      .loader(path.resolve(__dirname, '../build/md-loader/index.js'))
      .end()

  }
}

```

**Comment by ocean95966** [comment]
@cuixiaorui  支持ts 里面的写法要改造吗 还是只要引入依赖 入口文件改成ts就行了
