### ISSUE TITLE
重构 Upload 组件

### ISSUE THREAD

**Issue by ImJustAMan** [hug-sun/element3#53]
## Tasking

- [ ] 解决逻辑报错
- [ ] 使用 composition api 重构逻辑
- [ ] 更新使用文档

## Comment

**Comment by shengxinjing** [comment]
重新开放占位

**Comment by trueLoving** [comment]
这个组件我承包了。doing

**Comment by liushuiyuan001** [comment]
@trueLoving 请问你还开发吗?要不开发了我就接手了

**Comment by liushuiyuan001** [comment]
@shengxinjing 没人响应这个组件我就承包了

**Comment by liushuiyuan001** [comment]
重构完成,剩余test待补充

**Comment by shengxinjing** [comment]
@liushuiyuan001 可以先把逻辑代码提交 我给你merge

**Comment by Arrow-zb** [comment]
好不容易重构还写了测试，结果被关了，👀o(╥﹏╥)oo(╥﹏╥)oo(╥﹏╥)o

**Comment by Arrow-zb** [comment]
看了现在的upload组件，觉得有可优化的点，还有没有写测试，我可以不可以拉下来优化并且把测试加上呀

**Comment by liushuiyuan001** [comment]
> 好不容易重构还写了测试，结果被关了，👀o(╥﹏╥)oo(╥﹏╥)oo(╥﹏╥)o

兄弟,你看我comment时间,组件是我认领,代码其实早写好了,比你早了快一周了.

**Comment by liushuiyuan001** [comment]
> 看了现在的upload组件，觉得有可优化的点，还有没有写测试，我可以不可以拉下来优化并且把测试加上呀
Test这两天就会提交pr.至于优化等等你可以提交pr.
@Arrow-zb

**Comment by shengxinjing** [comment]
@Arrow-zb 难道有误伤，前几天清理了一波，最近还有很多可以提，比如bug，测试，文档 都可以的 优先给你merge

**Comment by caikan** [comment]
@liushuiyuan001 已经在做了的话，可以把PR先发出来，完成之前可以在PR标题加上 `WIP:` 前缀，完成后再去掉，也能方便大家随时review

**Comment by liushuiyuan001** [comment]
> @liushuiyuan001 已经在做了的话，可以把PR先发出来，完成之前可以在PR标题加上 `WIP:` 前缀，完成后再去掉，也能方便大家随时review

@caikan 下午应该会把test pr提交上

**Comment by imjsxu** [comment]
这个组件这么吃香呀，哈哈哈哈

**Comment by cuixiaorui** [comment]
已经完成重构
