### ISSUE TITLE
重构 Rate 组件

### ISSUE THREAD

**Issue by ImJustAMan** [hug-sun/element3#54]
## Tasking

- [x] 解决逻辑报错
- [ ] 使用 composition api 重构逻辑
- [ ] 更新使用文档
- [ ] 等待 Form 开发完成

## Comment

**Comment by ImJustAMan** [comment]
等待form开发完成 不属于无人修改状态

**Comment by Hanhh** [comment]
占个位

**Comment by fqcto** [comment]
占个位. pis：还不错，就是有些组件特殊地方bug存在
