### ISSUE TITLE
发现了一个BUG，Element3 Slider 滑块组件在VUE3中+Electron中，开发模式serve看正常，build成exe后，发现Slider滑块，拖不动。请核实一下！

### ISSUE THREAD

**Issue by tanker5258** [hug-sun/element3#545]
### Bug description

发现了一个BUG，Element3 Slider 滑块组件在VUE3中+Electron中，开发模式serve下一切正常，build成exe后，发现Slider滑块，拖不动。请核实一下！

 "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "electron:build": "vue-cli-service electron:build",
    "electron:serve": "vue-cli-service electron:serve",
    "postinstall": "electron-builder install-app-deps",
    "postuninstall": "electron-builder install-app-deps"
  },
  "main": "background.js",
  "dependencies": {
    "core-js": "^3.6.5",
    "element3": "^0.0.26",
    "jodit": "^3.5.4",
    "jodit-vue": "^2.2.3",
    "vue": "^3.0.0",
    "vuex": "^4.0.0-0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "@vue/eslint-config-prettier": "^6.0.0",
    "babel-eslint": "^10.1.0",
    "electron": "9.0.0",
    "electron-devtools-installer": "^3.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-prettier": "^3.1.3",
    "eslint-plugin-vue": "^7.0.0-0",
    "prettier": "^1.19.1",
    "sass": "^1.27.0",
    "sass-loader": "^10.0.4",
    "vue-cli-plugin-electron-builder": "^2.0.0-rc.5",
    "vue-cli-plugin-element3": "0.0.4"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/vue3-essential",
      "eslint:recommended",
      "@vue/prettier"
    ],
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "rules": {}
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]

**Comment by WumaCoder** [comment]
请写一个，最简单的Demo来展示问题
