### ISSUE TITLE
el-select runtime-core.esm-bundler.js?5c40:38 [Vue warn]: Property "$ELEMENT" was accessed during render but is not defined on instance.

### ISSUE THREAD

**Issue by MOONCOM** [hug-sun/element3#548]
### Bug description
代码如下所示
```
<el-select
    v-model="form.type"
    :placeholder="`请输入${title}类型`"
  >
    <el-option
      v-for="item in typeList"
      :key="item.id"
      :label="item.name"
      :value="item.id"
    />
  </el-select>
```
浏览器中报如下警告，但是不影响使用
![image](https://user-images.githubusercontent.com/34829622/105115114-378dc700-5b03-11eb-94bd-3ccffcd791b2.png)

**What is the current behavior?**

浏览器控制台中应该没有警告，例如这里使用el-input组件便不会有警告

**What is the expected behavior?**

**Steps to Reproduce**

1.
2.

**Environment**

- Element3 Version: `0.0.39`
- Node Version: `10.16.3`
- OS and version:

**Comment by MOONCOM** [comment]
浏览器中警告内容如下所示
runtime-core.esm-bundler.js?5c40:38 [Vue warn]: Property "$ELEMENT" was accessed during render but is not defined on instance. 
  at <ElSelect modelValue=undefined onUpdate:modelValue=fn placeholder="请输入文章类型" > 
  at <ElFormItem key=0 label="文章类型" > 
  at <ElCol span=8 > 
  at <ElRow> 
  at <ElForm inline=true model= {type: undefined, status: undefined, start: undefined, end: undefined, user: undefined, …} label-width="90px" > 
  at <TablePageSlot title="文章" class="article-review main-section" onSearch=fn<bound search> > 
  at <ArticleReview class="main-section" onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {setTypeList: ƒ, setTableMessage: ƒ, search: ƒ, …} > > 
  at <AsyncComponentWrapper class="main-section" onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {setTypeList: ƒ, setTableMessage: ƒ, search: ƒ, …} > > 
  at <RouterView class="main-section" > 
  at <ElScrollbar> 
  at <ElMain> 
  at <ElContainer> 
  at <ElContainer class="name" > 
  at <Home onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {…} > > 
  at <RouterView> 
  at <App>

**Comment by cuixiaorui** [comment]
是否可以提供一下完整代码

方便我这边复现一下

**Comment by MOONCOM** [comment]
> 是否可以提供一下完整代码
> 
> 方便我这边复现一下

你好，这是我的代码 [链接](https://codesandbox.io/s/brave-golick-p3qu4?file=/src/App.vue)
但是在线上的编辑器中却没有出现我上面说的[vue warn]警告信息，在我的本地代码中，只要将红框中的el-select删除，控制台便不会出现警告信息
![image](https://user-images.githubusercontent.com/34829622/105269401-c9aed180-5bce-11eb-99bd-651588bd173c.png)

**Comment by cuixiaorui** [comment]
你提供的 code ，并没有复现这个 warn 呀

还需要什么操作步骤嘛？

**Comment by MOONCOM** [comment]
我新创建了个项目试验了一下确实没有报错，我再研究一下，看看什么原因造成的

**Comment by cuixiaorui** [comment]
好的，有问题在及时反馈哈

**Comment by wangsitingting** [comment]
> 

+1

**Comment by gavinwyf** [comment]
+1
