### ISSUE TITLE
form组件验证时trigger事件不触发验证

### ISSUE THREAD

**Issue by xh-shen** [hug-sun/element3#549]
### Bug description
Form 表单组件在rules中定义的验证规则，只会在this.$refs.form. validate()触发验证，在trigger中声明的事件执行时不会触发表单验证

```js
const rules = {
    username: [{ required: true, message: '请输入用户名', trigger: 'blur' }],
    password: [{ required: true, message: '请输入密码', trigger: 'blur' }],
}
```
表单元素失去焦点不触发验证

**Environment**

- Element3 Version: `0.0.39`
- Node Version: `12.16.7`

**Comment by xh-shen** [comment]
Hello @cuixiaorui Please click the [link](https://codesandbox.io/s/new-cdn-b3yk7?file=/src/App.vue) to see the example

你好 @cuixiaorui  请点击  [链接](https://codesandbox.io/s/new-cdn-b3yk7?file=/src/App.vue) 查看示例

**Comment by tom-hanks** [comment]
是有这个问题0.0.39
