### ISSUE TITLE
类似于 input的 append slot 是不是可以有一个函数传递，以达到扩大点击范围。

### ISSUE THREAD

**Issue by mrandpz** [hug-sun/element3#550]
rt，可以以样式的形式去改动，但如果增加一个函数传递会不会更好点
![image](https://user-images.githubusercontent.com/20697372/105156264-8c066600-5b46-11eb-85c3-92905c15c2f3.png)

**Comment by cuixiaorui** [comment]
是否有可参考的 demo ？

着可以帮助我更容易理解你的需求哈

**Comment by mrandpz** [comment]
[demo](https://codesandbox.io/s/condescending-euler-6dj3j?file=/src/components/HelloWorld.vue)

**Comment by cuixiaorui** [comment]
你想要的是点击范围，这个本身就和样式有关系的

通过一个函数怎么控制？

可以提供下你的想法哈

比如，你希望的是这个函数是什么样的，使用方式是什么样的

**Comment by mrandpz** [comment]
类似以下代码
```html
 <div class="append" @click="handleClick" v-if="$slots.append">
        <slot name="append"></slot>
  </div>

...
const handleClick = ()=>{
      ctx.emit('appendClick')
      console.log('handleClick')
    };
```

```html
<TestSlot @appendClick="appendClick" someProps="someProps">
    <template v-slot:append>
      <div>append</div>
    </template>
  </TestSlot>
```

这样我传递一个click函数就可以点击到 append 的范围了，而不用去 reset 这个 style。

**Comment by cuixiaorui** [comment]
template 本身是不会渲染出来的，给了它一个点击范围，只能是写死的。

并且组件库并不能确定用户想扩大 click 范围具体是哪里

基于扩展性来讲，用户通过自定义样式会更好

感谢你的反馈
