### ISSUE TITLE
el-pagination的样式问题

### ISSUE THREAD

**Issue by guoguozhi** [hug-sun/element3#560]
.el-pagination__jump .el-input {
  margin-right: 4px;
}

.el-pagination__jump .el-input .el-input__inner {
  height: 28px;
}

**Comment by cuixiaorui** [comment]
??? 没看懂

可以提供一个 demo 

或者请按照模板填写 issues

**Comment by guoguozhi** [comment]
<img width="788" alt="Snipaste_2021-01-25_14-10-55" src="https://user-images.githubusercontent.com/24681394/105668133-ae69fc00-5f17-11eb-8ee4-fe3bc9ecb17e.png">
css样式的问题，还有'页'字前面的空格太小~

**Comment by WumaCoder** [comment]
正在重构该组件，即将解决
