### ISSUE TITLE
按需引入 Element3：  使用 setupGlobalOptions 设置全局配置对象_报错,

### ISSUE THREAD

**Issue by wanghai1** [hug-sun/element3#568]
### Bug description

elemet版本     "element3": "0.0.39",
官方示例
![image](https://user-images.githubusercontent.com/37146875/108965779-4cd4b300-76b8-11eb-9031-297b64e8292b.png)
实际显示没有type文件
![image](https://user-images.githubusercontent.com/37146875/108965837-5eb65600-76b8-11eb-8fe2-367a48af0c7a.png)

模块 ""../node_modules/element3/types"" 没有导出的成员 "setupGlobalOptions"。你是想改用 "import setupGlobalOptions from "../node_modules/element3/types"" 吗?ts(2614)

- Element3 Version: `x.x.x`
- Node Version: `x.x.x`
- OS and version:

**Comment by WumaCoder** [comment]
已经解决问题
