### ISSUE TITLE
重构 Table 组件

### ISSUE THREAD

**Issue by ImJustAMan** [hug-sun/element3#58]
## Tasking

- [ ] 解决逻辑报错
- [ ] 使用 composition api 重构逻辑
- [ ] 更新使用文档

## Comment

**Comment by 243001806** [comment]
此坑已有有人

**Comment by 57code** [comment]
table已收回

**Comment by Arrow-zb** [comment]
没人的话我来尝试吧，虽然有点多，但是是个机会！😺😺😺

**Comment by caikan** [comment]
看了一下，原版的table实现得太复杂了，貌似利用了一个单独的Vue实例作为store来缓存数据。此实例的创建依赖了Vue 2的`Vue.extend()` API，无法简单地迁移到Vue3。
如果利用Vue 3相关Composition API全部重新实现相关的数据缓存功能，感觉工作量会巨大。
我打算先尝试将store实例的创建过程改为Vue3兼容的写法，解决运行错误的问题。

**Comment by caikan** [comment]
继续看了下，除了主组件`el-table`用的是模板，其它关联子组件大量用到JSX。内部逻辑（包括单独实现的专用store）错综复杂，另外还有一些疑似未处理的遗留TODO。我尝试了使用`createApp()`来改写内部store的创建也失败了（就算能改成，其它问题也不好解决）感觉差不多只能全部重写了。有必要重新优化一下内部组件的组织结构。

**Comment by cuixiaorui** [comment]
已经完成
