### ISSUE TITLE
使用element3打包后报错

### ISSUE THREAD

**Issue by 2205522593** [hug-sun/element3#584]
项目中使用element3+vite2+ts构建，当我打包的时候，会报很多element3的内部声明文件错误，如下图所示：
![image](https://user-images.githubusercontent.com/24216747/112322364-ca0d3b00-8ceb-11eb-8821-1de732c43586.png)
请问我改如何解决这些错误

**Comment by WumaCoder** [comment]
能否给一个最小重现Demo的repo

**Comment by amadeus711** [comment]
## 问题补充
使用vite最新提供的构建方案，即先使用 vue-tsc 类型检查然后再构建时，类型检查步骤出现报错：

<img width="1205" alt="error" src="https://user-images.githubusercontent.com/46394163/117261774-1dde7880-ae83-11eb-9169-238b6c51477d.PNG">

### 复现仓库地址：https://github.com/amadeus711/issue-helper

### 复现步骤：拉取代码、安装完毕，执行 npm run build

@WumaCoder @cuixiaorui
