### ISSUE TITLE
El-Form: vue ref attribute overlaps field with the same name

### ISSUE THREAD

**Issue by bearbattle** [hug-sun/element3#595]
### Bug description

When using `<el-form>`, giving the form with `ref` attribute the same as `model` attribute would cause inappropriate behaviour of accessing data field associated with the `model` attribute.

**What is the current behavior?**

Given the code below:

```vue
<template>
	<el-form
        ref="form"
        :model="form"
    >
    </el-form>
</template>

<script lang="ts">
import { defineComponent, reactive } from 'vue'
export default defineComponent({
  name: 'BugReport',
  setup() {
    const form = reactive({ foo: 'bar'})
    return {
      form,
    }
  },
  mounted() {
    console.log(this.form) // This gives the content of *`<el-form>`* rather than `{foo: 'bar'}`
  }
})
</script>
```

**What is the expected behavior?**

`this.form` should provide the content of filed previously defined.

**Steps to Reproduce**

Refer to code above.

Live Demo:

<a href="https://codepen.io/bearbattle/pen/NWjzVxP">
  Bug Report for Element3</a>

**Environment**

- Element3 Version: `0.0.40`
- Node Version: `v14.17.3`
- OS and version: `Windows 10 LTSC 2019 (Version 1809)`

**Comment by shawroger** [comment]
Perhaps it can be in this way.

Avoid using option-style `mounted` api, use `onMounted` instead.

```ts
import { defineComponent, reactive, onMounted } from 'vue'
export default defineComponent({
  name: 'BugReport',
  setup() {
    const form = reactive({ foo: 'bar'})
    onMounted(() => console.log(form));
    return {
      form,
    }
  },
})
```
