### ISSUE TITLE
element-plus和element3到底哪个是正规的？

### ISSUE THREAD

**Issue by ike-yu-byte** [hug-sun/element3#610]
### Bug description

**What is the current behavior?**

**What is the expected behavior?**

**Steps to Reproduce**

1.
2.

**Environment**

- Element3 Version: `x.x.x`
- Node Version: `x.x.x`
- OS and version:

**Comment by Cikayo** [comment]
用 element-plus，目前有人维护，更新频率高
element3跟新频率有点低
