### ISSUE TITLE
Divider component add color and style attribute

### ISSUE THREAD

**Issue by JayMeDotDot** [hug-sun/element3#614]
### Color Attribute
Allow developers to set the divider component's color with CSSProperties.
With no prop value passed, it will fall back to the default value.
In addition, the text color would inherit from the divider component.
The default value may be `$--border-color-base`.

### Style Attribute
Allow developers to set the divider component's style with CSSProperties.
With no prop value passed, it will fall back to the default value.
The default value may be `solid`.

**Comment by shengxinjing** [comment]
pr welcome

**Comment by withoutmelv** [comment]
申领

**Comment by JayMeDotDot** [comment]
> 申领

不好意思啊，这个 feature 已经实现了，但是我忘记关闭了，你可以看下有没有需要改进的地方😊
如果没问题的话，我就关闭这个 issue 了
