### ISSUE TITLE
lint 和 lint:fix 应该对项目中除了被 ignore 掉的所有文件生效

### ISSUE THREAD

**Issue by LoTwT** [hug-sun/element3#629]
### Bug description

**What is the current behavior?**

- package.json 中 `lint` 和 `lint:fix` 只对 `src` 和 `scripts` 下的部分扩展名结尾的文件生效

- 比如 `vitest.config.ts` 没有被 lint 到，有格式错误

**What is the expected behavior?**

- `lint` 和 `lint:fix` 应该对项目中除了被 ignore 掉的所有文件生效

**Comment by shengxinjing** [comment]
好提议
