### ISSUE TITLE
Progress 组件开发

### ISSUE THREAD

**Issue by JayMeDotDot** [hug-sun/element3#652]
属性 | 说明 | 类型 | 可选值 | 默认值
-- | -- | -- | -- | --
type | 进度条类型 | string | line \| circle \| dashboard | line
status | 进度条状态 | string |  success \| error \| warning \| info | -
color | 进度条颜色 | string | ccsProperties | —
propcessing | 处理中的状态 | boolean | true \| false | false
percentage | 百分比值 | number | 0 ~ 100 | 0
indicator-placement | 指标显示位置 | string | inside \| outerside | outerside
show-indicator | 是否显示指标 | boolean | true \| false | true
height | 进度条高度 | number | — | —

各个属性详细说明：

- [x] type
- 属性的样式切换可以通过传值来切换子组件来控制

- [x] status
- 当设置进度条状态时，会显示相应图案，不再显示数值百分比值

- [x] color
- 用户自定义颜色

- [x] processing
- 让进度条拥有进行时的动效 
- [x] percentage
- 传入百分比
- 当设置 status 属性时，百分比值不再显示
- [x] indicator-placement
- 控制百分比数值显示的位置
- 当设置 status 属性，本属性失效
- [x] show-indicator
- 控制是否显示百分比数值或者状态图案
- [x] height
- 当高度变高时，百分比或 status 图案依旧居中

**Comment by JayMeDotDot** [comment]
自己给自己布置的任务

**Comment by aiyoudiao** [comment]
申领
